Update sync.yml

diff --git a/.github/workflows/sync.yml b/.github/workflows/sync.yml
--- a/.github/workflows/sync.yml
+++ b/.github/workflows/sync.yml
@@ -97,7 +97,12 @@ jobs:
           sudo touch /mnt/failed-repos
           sudo chown runner:runner -R /mnt/sync /mnt/failed-repos
 
-          sync_mirror() {
+          function log() {
+            # echo "[$repo]" "${@}"
+            echo "${@}"
+          }
+
+          function sync_mirror() {
             set -e
 
             url=$(jq -r '.clone_url' <<< "$config")
@@ -107,18 +112,18 @@ jobs:
 
             mkdir "$repo" && cd "$repo"
 
-            echo "[$repo] Check if the mirror repository is created"
+            log "Check if the mirror repository is created"
             set +e
             curl -I --fail --silent --show-error -o /dev/null "https://github.com/aosp-mirror-neo/$repo"
             ret="$?"
             set -e
             if [ "$ret" -ne 0 ]; then
-              echo "[$repo] Creating target repo"
+              log "Creating target repo"
               gh repo create "aosp-mirror-neo/$repo" --homepage "$url" --disable-issues --disable-wiki --public --description "$description"
               first="1"
             fi
 
-            echo "[$repo] Compare remotes"
+            log "Compare remotes"
             git ls-remote --quiet --heads --tags "$url" > remote-src &
             git ls-remote --quiet --heads --tags "https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/aosp-mirror-neo/$repo" > remote-dist &
             wait
@@ -127,11 +132,11 @@ jobs:
             ret="$?"
             set -e
             if [ "$ret" -eq 0 ]; then
-              echo "[$repo] Mirror is synchronized. skip"
+              log "Mirror is synchronized. skip"
               return
             fi
 
-            echo "[$repo] Cloning source repo"
+            log "Cloning source repo"
             mkdir repo-dir && cd repo-dir
             git init --bare
             git remote add --mirror=fetch origin "$url"
@@ -145,22 +150,37 @@ jobs:
             git config set --append remote.mirror.fetch '+refs/tags/*:refs/tags/*'
 
             if [ "$first" -eq 0 ]; then
+              log "Fetching from mirror"
               git fetch --quiet mirror --filter=blob:none
-              git fetch --quiet --prune origin
-              ret="$?"
-            else
-              echo "[$repo] First time sync. full cloning"
+              log "Fetching from origin"
               git fetch --quiet origin
-              ret="$?"
+            else
+              log "First time sync. full cloning"
+              git fetch --quiet origin
             fi
 
-            if [ "$ret" -ne 0 ]; then
-              echo "[$repo] failed to fetch. (err: $?)"
-              return
-            fi
-
-            echo "[$repo] Pushing to mirror repo"
+            log "Pushing to mirror repo"
+            set +e
             git push --quiet --mirror mirror
+            ret="$?"
+            set -e
+            if [ "$ret" -eq 0 ]; then
+              log "Failed to push, fallback"
+              COMMIT_REVS=$(git rev-list --reverse HEAD)
+              COUNT=0
+              BATCH=60000
+
+              for REV in $COMMIT_REVS; do
+                  COUNT=$((COUNT + 1))
+                  if [ $((COUNT % BATCH)) -eq 0 ]; then
+                      echo "Pushing up to commit $COUNT..."
+                      git push mirror $REV:refs/heads/$(git branch --show-current)
+                  fi
+              done
+
+              git push mirror --mirror
+            fi
+
             gh repo edit "aosp-mirror-neo/$repo" --default-branch "$( git remote show origin | grep "^  HEAD branch: " | cut -c 16- )"
           }
 
@@ -181,18 +201,18 @@ jobs:
               repo=$(echo "$config" | jq -r '.name' | tr '/' '_')
               status="OK"
               echo "::group::$repo"
-              echo "[$repo] Start"
+              log "Start"
               if ! sync_mirror "$config"; then
-                echo "[$repo] Failed"
+                log "Failed"
                 echo "$repo" >> /mnt/failed-repos
                 status="Failed"
               fi
               echo >&3
-              echo "[$repo] Cleaning"
+              log "Cleaning"
               cd "/mnt/sync/$repo"
               rm -rf repo-dir remote-src remote-dist
               end_time=$(date +%s.%N)
-              echo "[$repo] Done ($status) ($CURRENT/$TOTAL_COUNT) ($(echo "$end_time - $start_time" | bc) sec)"
+              log "Done ($status) ($CURRENT/$TOTAL_COUNT) ($(echo "$end_time - $start_time" | bc) sec)"
               echo "::endgroup::"
             )
             # )&
@@ -216,21 +236,3 @@ jobs:
         run: |
           cat /mnt/failed-repos
           echo "list=$(cat /mnt/failed-repos)" >> $GITHUB_OUTPUT
-
-      - uses: beacon-biosignals/matrix-output@v1
-        if: always()
-        id: matrix-output
-        with:
-          yaml: |
-            list: ${{ steps.failed.outputs.list }}
-
-  status:
-    name: Status
-    needs: main
-    runs-on: ubuntu-latest
-    steps:
-      - name: List
-        env:
-          LIST: ${{ needs.main.outputs.failed }}
-        run: |
-          echo "$LIST" | jq -cr '.[].list'
