Update sync.yml

diff --git a/.github/workflows/sync.yml b/.github/workflows/sync.yml
--- a/.github/workflows/sync.yml
+++ b/.github/workflows/sync.yml
@@ -29,7 +29,7 @@ jobs:
       - name: Split
         id: split
         run: |
-          PARALLEL=25
+          PARALLEL=24
           MATRIX=$(curl -s "https://android.googlesource.com/?format=JSON" | tail -n +2 | jq -c '.[]' | shuf | \
                     split -n l/$PARALLEL --filter='jq -Rs .' | jq -sc .)
           echo "matrix=$MATRIX" >> $GITHUB_OUTPUT
@@ -270,4 +270,7 @@ jobs:
         id: failed
         run: |
           cat /mnt/failed-repos
-          echo "list=$(cat /mnt/failed-repos)" >> $GITHUB_OUTPUT
+          # echo "list=$(cat /mnt/failed-repos)" >> $GITHUB_OUTPUT
+          if [[ -s /mnt/failed-repos ]]; then
+            exit 1
+          fi
